# Your Name or Company
title: Rushang Karia

# Description of your website. This is used for social sharing.
description:  Ph.D. student at ASU.

# A brief blurb about yourself
content: Hello! I'm a Ph.D. student at <a href="https://www.asu.edu" style="text-decoration:none">Arizona State University</a> studying 
    Computer Science in the <a href="https://cidse.engineering.asu.edu/" style="text-decoration:none">School of
    Computing, Informatics, and Decision Systems Engineering (CIDSE)</a>. I work in the 
    <a href="https://aair-lab.github.io/" style="text-decoration:none">Autonomous Agents and Intelligent Robots (AAIR)</a> lab with 
    <a href="https://www.public.asu.edu/~ssriva43/" style="text-decoration:none">Dr. Siddharth Srivastava</a> as my advisor.
    
    <br>
    <br>
    
    My research is concentrated in the fields of Artificial Intelligence and Machine Learning. Focus areas include&#58;-
    <ul style="margin-top:-30px;"> <!-- https://stackoverflow.com/questions/7759229/remove-space-between-paragraph-and-unordered-list -->
        <li>Automated Planning</li>
        <li>Abstraction</li>
        <li>Generalized Planning</li>
        <li>Reinforcement Learning</li>
    </ul>
    
    Prior to my Ph.D., I worked as a Firmware Engineer at SanDisk (now Western Digital) from 2016-2019, where I was 
    involved in the development of firmware for enterprise SSDs (solid state drives). 

    <p></p>
    
    <p>
    Still reading? Waow, umm thanks! To know more about me (including my love for memes), head over to the Bio 
    (which is still under construction) or just send me a message at 
    <a href="mailto:Rushang.Karia@asu.edu">Rushang.Karia@asu.edu</a>.
    </p>
    
    
# Add your social links
#social:
#  - platform: github
#    url: https://github.com/brianmaierjr
# - platform: facebook
#   url: https://facebook.com/brianmaierjr
# - platform: twitter
#   url: https://twitter.com/brianmaierjr
# - platform: linkedin
#   url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
